# Scientific Computing with Python
## June 02 2020
## 3rd LBRN-LONI Scientific Computing Bootcamp

# Outline

 * Day 1 Basic Python Review
 * Introducing Python Modules: 
     - Numpy
     - Scipy
 * Examples:
     - Calculate deriving of a function
     - Convert RGB image to Grayscale
     - Simple regression example
 * Excercise (will be talked about in the afternoon session)

# Day 1 Basic Python Recap

 * Python is a general-purpose interpreted, interactive, object-oriented, and high-level programming language.
 * It was created by Guido van Rossum during 1985-1990. Like Perl, Python source code is also available under the GNU General Public License (GPL).

### Demostration of Python Loop

In [0]:
a = list(range(5))
print(a)

[0, 1, 2, 3, 4]


In [0]:
for idx in range(len(a)):
    a[idx] += 5
print(a)

[5, 6, 7, 8, 9]


### Python Tuples
- A tuple is a sequence of immutable Python objects. Tuples are sequences, just like lists. 
- The differences between tuples and lists are, the tuples cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.

In [0]:
tup1 = ('physics', 1997, 'chemistry', 2000); 
print(tup1)

('physics', 1997, 'chemistry', 2000)


In [0]:
tup2 = (1, 2, 3, 4, 5);
print(tup2)

(1, 2, 3, 4, 5)


In [0]:
tup3 = "a", "b", "c", "d";
print(tup3)

('a', 'b', 'c', 'd')


In [0]:
tup4 = 3, 5, 7
print(tup4)

(3, 5, 7)


In [0]:
# The empty tuple is written as two parentheses containing nothing
tup1 = ();
print(tup1)

()


In [0]:
# To write a tuple containing a single value you have to include a comma,
tup1 = (50,);
print(tup1)

(50,)


In [0]:
tup1a = 50,
print(tup1a)

(50,)


In [0]:
# Accessing Values in Tuples
print("tup1[0]: ", tup1[0])

tup1[0]:  50


In [0]:
#tuples are immutable, they cannot be changed
tup1[0]=5

TypeError: ignored

In [0]:
print("tup2[1:5]: ", tup2[1:5])

tup2[1:5]:  (2, 3, 4, 5)


In [0]:
# Updating Tuples, create a new tuple as follows
tup3 = tup1 + tup2
print(tup3)

(50, 1, 2, 3, 4, 5)


In [0]:
# delete tuple elements
print("Deleting tup3 : ")
del tup3;
print(tup3) # this will reture an error

Deleting tup3 : 


NameError: ignored

# Numpy Overview
- NumPy (Numeric Python) is the fundamental package for scientific computing in Python.
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices)
- An assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- In short , NumPy package provides basic routines for manipulating large arrays and matrices of numeric data. 

# Simple array math using np.array.
* A numpy array is a grid of values.
* All of the elements have the same type.
* NumPy array starts its index from 0, end at N-1 (C-style)

In [0]:
import numpy as np # an alias for the namespace
a = np.array([1,2,3])
b = np.array((4,5,6))

In [0]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [0]:
print(a+1)
print(b*2)

[2 3 4]
[ 8 10 12]


In [0]:
print(a+b)

[5 7 9]


In [0]:
print(a*b)

[ 4 10 18]


In [0]:
print(a ** b)

[  1  32 729]


* Setting Array Element Values

In [0]:
a[0]=11
print(a)

[11  2  3]


In [0]:
a.fill(0) # set all values in the array with 0
print(a)

[0 0 0]


In [0]:
a[:]=1 # why we need to use [:]?

In [0]:
print(a)
print(a.dtype) # note that a is still int64 type !
print(type(a))

[1 1 1]
int64
<class 'numpy.ndarray'>


In [0]:
a[0]=10.6 # decimal parts are truncated, be careful!
print(a)

In [0]:
a.fill(-3.7) # fill() will have the same behavior
print(a)

#### Create floating value arrays

In [0]:
a = np.array([1,2,3.1])
print(a)
print(a.dtype)

In [0]:
a = np.array([1,2,3],dtype=float)
print(a)

In [0]:
a = np.array([1,2,3]).astype(float)
print(a)

* #### Numpy Array Properties

In [0]:
a = np.array([0,1,2,3]) # create a from a list
print(a)

In [0]:
# shape returns a tuple listing the length of the array
print(a.shape) # or np.shape(a)

In [0]:
print(a.size) # or np.size(a), return the total number of elements
# return the number of dimensions of the array
print(a.ndim)

* #### Numpy Array Creation Functions
- Numpy's arange is nearly identical to Python’s `range()`. Creates an array of values in the range [start,stop,step) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values

In [0]:
a = np.arange(4)
print(a)

In [0]:
a = np.arange(0,4)
print(a)

In [0]:
a = np.arange(4,dtype=float)
print(a)

In [0]:
a = np.arange(1.5,2.4,0.3)
print(a)

In [0]:
a = np.arange(0, 2*np.pi, np.pi/4)
print(a)

* #### Useful initial value creation

In [0]:
a = np.ones((2,3)) # need to supply tuple as shape of the array!
print(a)
print(a.dtype)

In [0]:
a = np.zeros((3,3)) # need to supply tuple as shape of the array!
print(a)
print(a.dtype)

In [0]:
a = np.identity(4)
print(a)

In [0]:
a = np.eye(4,dtype=int)
print(a)
print(a.dtype)

In [0]:
a = np.empty(2)
print(a)
a.fill(5.0)
print(a)
a[:] = 4.0
print(a)

* #### `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`
Return evenly spaced numbers over a specified interval.

In [0]:
a = np.linspace(0,1,5)
print(a)

* #### `numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)`

Return numbers spaced evenly on a log scale.

The sequence starts at base ** start (base to the power of start) and ends with base ** stop (see endpoint below).

In [0]:
#import matplotlib.pyplot as plt
a = np.logspace(0,1,5)
print(a)
#plt.plot(a,'r-s')
#plt.plot(np.log(a),'b-s')

In [0]:
a = np.logspace(2.0, 3.0, num=4, base=2.0)
print(a)

* #### Array from/to ASCII files
use loadtxt

`data.txt`<br>
  `Index`<br>
`Brain Weight`<br>
`Body Weight`<br>
`#here is the training set`<br>
`1 3.385 44.500 abjhk`<br>
`2 0.480 33.38 bc_00asdk`<br>
`...`<br>
`#here is the cross validation set`<br>
`6 27.660 115.000 rk`<br>
`7 14.830 98.200 fff`<br>
`...`<br>
`9 4.190 58.000 kij`<br>

In [0]:
# download the file to local virtual machine
! if [ ! -f "data.txt" ]; then wget 'https://raw.githubusercontent.com/lsuhpchelp/lbrnloniworkshop2020/master/day2/data.txt'; else echo 'file exists'; fi;
! cat data.txt

In [0]:
# np.loadtxt can directly load a txt from a URL
#weburl = 'https://raw.githubusercontent.com/lsuhpchelp/lbrnloniworkshop2020/blob/master/day2/'
#txtfile = weburl + 'data.txt'

# we will use the file locally on the virtual machine
txtfile = 'data.txt'
a = np.loadtxt(txtfile,skiprows=16,usecols={0,1,2},dtype=None,comments="#")
print(a)

Using genfromtxt

In [0]:
# np.genfromtxt can guess the actual type of your columns by using dtype=None
a = np.genfromtxt(txtfile,skip_header=16,dtype=None,encoding='ascii')
print(a)

* #### Reshaping Arrays

In [0]:
a = np.arange(6)
print(a)
print(a.shape)

In [0]:
a.shape = (2,3) # reshape array to 2x3
print(a)

In [0]:
a = a.reshape(3,2) # reshape array to 3x2
print(a)
# a.reshape(2,5) # cannot change the number of elements in the array
# Traceback (most recent call last):
# File "<stdin>", line 1, in <module>
# ValueError: total size of new array must be unchanged

In [0]:
a = a.reshape(2,-1) # numpy determines the last dimension
print(a)

In [0]:
a = a.reshape(-1,2)
print(a)

* #### Flattening Multi-dimensional Arrays

In [0]:
a = np.arange(12).reshape(-1,4)
print(a)

In [0]:
# a.flatten() converts a multidimensional array into
# a 1-D array. The new array is a copy of the original data.
b = a.flatten()
print(b)

# Numpy is easy and fast!
## Rule of thumb: 
> ### Removing loops using NumPy

In [0]:
# we use the timeit (measure execution time of small code snippets) function 
a=list(range(100000))
result_loop = %timeit -o b = [val+5 for val in a]
print("best result using for loop: %f sec" % (result_loop.best,))

In [0]:
a=np.array(a)
result_ufunc = %timeit -o a+5
print("best result using ufunc: %f sec" % (result_ufunc.best,))

In [0]:
speedup = result_loop.best/result_ufunc.best
print("speedup=%.1f times" % (speedup,))

# Four Tools in Numpy
1. Ufunc (Universal Function)
1. Aggregation
1. Broadcasting
1. Slicing, masking and fancy indexing

### Why Numpy is fast? 
- Avoid type check overhead
- Vectorization (simplified)
 - The process of rewriting a loop so that instead of processing a single element of an array N times, it processes (say) 4 elements of the array simultaneously N/4 times. 
- Many of the built-in functions are implemented in compiled C code.
 - They can be much faster than the code on the Python level

### Ufunc: Many ufuncs available
- Arithmetic Operators: `+ - * / // (floor division) % **`
- Bitwise Operators: `& | ~ ^ >> <<`
- Comparison Oper’s: `< > <= >= == !=`
- Trig Family: `np.sin, np.cos, np.tan ...`
- Exponential Family: `np.exp, np.log, np.log10 ...`
- Special Functions: `scipy.special.*`
- . . . and many, many more.

* #### Demostration of Ufunc

In [0]:
x = np.linspace(0,np.pi)
print(x)

In [0]:
x *= 2
print(x)

In [0]:
y = np.sin(x)
print(y)

In [0]:
import matplotlib.pyplot as plt
plt.plot(x,y)
plt.show()

### Aggregation Functions

- Aggregations are functions which summarize the values in an array (e.g. min, max, sum, mean, etc.)
- Numpy aggregations are much faster than Python built-in functions

- All have the same call style:

    `np.min() np.max() np.sum() np.prod()`<br>
`np.argsort()`<br>
`np.mean() np.std() np.var() np.any()`<br>
`np.all() np.median() np.percentile()`<br>
`np.argmin() np.argmax() . . .`<br>
`np.nanmin() np.nanmax() np.nansum(). . .`<br>

<!--
<img src="figure/np_aggregation.png", style="float: left;", width="300">
-->

![myphoto](https://github.com/lsuhpchelp/lbrnloniworkshop2020/raw/master/day2/figure/np_aggregation.png)


In [0]:
# Numpy Aggregation - Array Calculation
a=np.arange(6).reshape(2,-1)
print(a)

In [0]:
# by default a.sum() adds up all values
print(a.sum())

In [0]:
# same result, functional form
print(np.sum(a))

In [0]:
# sum along different axis
print(np.sum(a,axis=0))

In [0]:
print(np.sum(a,axis=1))

In [0]:
print(np.sum(a,axis=-1))

In [0]:
# product along different axis
print(np.prod(a,axis=0))

In [0]:
print(a.prod(axis=1))

In [0]:
# Numpy Aggregation – Statistical Methods
np.set_printoptions(precision=4)
# generate 2x3 random float array
a=np.random.random(6).reshape(2,3)
print(a)

In [0]:
print(a.mean(axis=0))

In [0]:
print(a.mean(axis=1))

In [0]:
print(a.mean())

In [0]:
print(np.mean(a))

In [0]:
# average can use weights
# avg = sum(a * weights) / sum(weights)
print(np.average(a,weights=[1,2,3],axis=1))

In [0]:
# standard deviation
print(a.std(axis=0))

In [0]:
# variance
print(np.var(a, axis=1))

In [0]:
# min/max operation
print(a.min())

In [0]:
print(np.max(a))

In [0]:
# find index of the minimum
print(a.argmin(axis=0))

In [0]:
print(np.argmax(a,axis=1))

In [0]:
# this will return flattened index
print(np.argmin(a))

In [0]:
print(a.argmax())

### Array Broadcasting

- Broadcasting is a set of rules by which ufuncs operate on arrays of different sizes and/or dimensions.
- Broadcasting allows NumPy arrays of different dimensionality to be
combined in the same expression.
- Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

### Broadcasting Rules
- In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one. If this condition is not met, a ValueError('frames are not aligned') exception is thrown indicating that the arrays have incompatible shapes. 
- The size of the result array created by broadcast operations is the maximum size along each dimension from the input arrays.

<!--
<img src="figure/np_broadcast.png", align="left", width="500"></br>
-->

![myphoto](https://github.com/lsuhpchelp/lbrnloniworkshop2020/raw/master/day2/figure/np_broadcast_scale.png)





<!--
<img src="figure/np_broadcast_error.png", align="left", width="200">
-->

![myphoto](https://github.com/lsuhpchelp/lbrnloniworkshop2020/raw/master/day2/figure/np_broadcast_error.png)

In [0]:
a = np.arange(3)
print("a=",a)
b = 5
print("b=",b)
print("a+b=",a+b)

In [0]:
a = np.arange(3).reshape(-1,1)
print("a=")
print(a)
b = 5
print("b=")
print(b)
print("a+b=")
print(a+b)

In [0]:
a = np.ones((3,3))
print("a=")
print(a)
b = np.arange(3)
print("b=")
print(b)
print("a+b=")
print(a+b)

In [0]:
a = np.ones((3,3))
print("a=")
print(a)
b = np.arange(3).reshape(-1,1)
print("b=")
print(b)
print("a+b=")
print(a+b)

In [0]:
a = np.arange(3).reshape(3,1)
print("a=")
print(a)
b = np.arange(3)
print("b=")
print(b)
print("a+b=")
print(a+b)

In [0]:
a=np.arange(6).reshape(3,2)
print("a=")
print(a)
b = np.arange(3)
print("b=")
print(b)
# this will raise an error
print(a + b)

### Slicing, Masking and Fancy Indexing

- `arr[lower:upper:step]`
- Extracts a portion of a sequence by specifying a lower and upper bound. The lower-bound element is included, but the upper-bound element is not included. Mathematically: `[lower, upper)`. The step value specifies the stride between elements

In [0]:
# indices: 0 1 2 3 4
# negative indices:-5 -4 -3 -2 -1
a = np.array([10,11,12,13,14])
# The following slicing results are the same

In [0]:
print(a[1:3])

In [0]:
print(a[1:-2])

In [0]:
print(a[-4:3])

In [0]:
# Omitting Indices: omitted boundaries are assumed to be the beginning
# or end of the list, compare the following results
print(a[:3])

In [0]:
print(a[-2:])

In [0]:
print(a[1:]) # from 1st element to the last

In [0]:
print(a[:-1]) # from 1st to the second to last

In [0]:
print(a[:]) # entire array

In [0]:
print(a[::2]) # from 1st, every other element (even indices)

In [0]:
print(a[1::2]) # from 2nd, every other element (odd indices)

* #### Multidimensional Arrays

In [0]:
# A few 2D operations similar to the 1D operations shown above
a = np.array([[ 0, 1, 2, 3],[10,11,12,13]], float)
print(a)

In [0]:
print(a.shape,a.size)

In [0]:
print(a.ndim) # number of dimensions

In [0]:
print(a[1])

In [0]:
print(a[1,3]) # reference a 2D array element

In [0]:
a[1,3] = -1 # set value of an array element

In [0]:
print(a[1]) # address second row using a single index

In [0]:
a = np.arange(1,26)
a = a.reshape(5,5) # generate the 2D array
print(a)

In [0]:
print(a[0,3:5])

In [0]:
print(a[0,3:4])

In [0]:
print(a[4:,4:])

In [0]:
print(a[3:,3:])

In [0]:
print(a[:,2])

In [0]:
print(a[2::2,::2])

### Slices Are References
- Slices are references to memory in the original array
- Changing values in a slice also changes the original array !

In [0]:
a = np.arange(5)
print(a)

In [0]:
b = a[2:4]
print(b)

In [0]:
b[0]=7
print(a)

### Masking

In [0]:
a = np.arange(10)
print(a)

In [0]:
# creation of mask using ufunc
mask=np.abs(a-5)>2
print(mask)

In [0]:
print(a[mask])

In [0]:
b=a[mask]
# manual creation of mask
mask=np.array([0,1,0,1,0],dtype=bool)
print(mask)
print(b[mask])

### 2D Masking
<!--
<img src="https://github.com/lsuhpchelp/lbrnloniworkshop2018/raw/master/day2_python/figure/masking_2d.png", style="float: left;", width="250">
-->


![masking 2d](https://github.com/lsuhpchelp/lbrnloniworkshop2020/raw/master/day2/figure/masking_2d_scale.png)

In [0]:
a=np.arange(25).reshape(5,5)+10
print(a)

In [0]:
mask=np.array([0,1,1,0,1],dtype=bool)
print(a[mask]) # on rows, same as a[mask,:]

In [0]:
print(a[:,mask]) # on columns

### Fancy Indexing - 1D
- NumPy offers more indexing facilities than regular Python sequences.
- In addition to indexing by integers and slices, arrays can be indexed by arrays of integers and arrays of Booleans (as seen before).

In [0]:
a=np.arange(8)**2
print(a)
# indexing by position
i=np.array([1,3,5,1])
print(a[i])

### Fancy Indexing - 2D
<!--
<img src="figure/fancy_indexing_2d.png", style="float: left;", width="200">
-->
![masking 2d](https://github.com/lsuhpchelp/lbrnloniworkshop2020/raw/master/day2/figure/fancy_indexing_2d_scale.png)

In [0]:
b=(np.arange(12)**2).reshape(3,-1)
print(b)
i=[0,2,1]
j=[0,2,3]
# indexing 2D array
print(b[i,j])

In [0]:
# note the shape of the resulting array
i=[[0,2],[2,1]]
j=[[0,3],[3,1]]
# When an array of indices is used,
# the result has the same shape as the indices;
print(b[i,j])

## Example of using masking, and plotting

In [0]:
x = np.linspace(-np.pi, np.pi, 30,endpoint=True)
y = np.sin(x)

In [0]:
import matplotlib.pyplot as plt
plt.plot(x,y,'b-s')
plt.show()

In [0]:
# plot the y>0 part
mask = y>0
print(mask)
print(x[mask])

In [0]:
plt.plot(x,y,'b-s')
plt.plot(x[mask],y[mask],'r-o')
plt.show()

In [0]:
mask1 = (y<0) & (x>-np.pi/2)

In [0]:
# plot between -pi/2 and pi/2
plt.plot(x,y,'b-s')
plt.plot(x[mask1],y[mask1],'m-^')
plt.show()

# Examples
## 1. Calculate Derivative of a function

In [0]:
"""
Calculate Derivative
--------------------
"""
import numpy as np
import matplotlib.pyplot as plt

# calculate the sin() function on evenly spaced data.
x = np.linspace(0,2*np.pi,101)
y = np.sin(x)

# use slicing to get dy and dx
dy=y[1:]-y[:-1]
dx=x[1:]-x[:-1]

dy_dx = dy/dx
cx = 0.5*(x[1:]+x[:-1])

In [0]:
# plt.subplot(1,2,1)
plt.plot(x,y)
plt.plot(cx,dy_dx,'xr')
plt.plot(x,np.cos(x),'-g')
plt.show()

## 2. Change RGB Image to Grayscale

In [0]:
# download the file to local virtual machine
! if [ ! -f "cat.jpg" ]; then wget 'https://raw.githubusercontent.com/lsuhpchelp/lbrnloniworkshop2020/master/day2/cat.jpg'; else echo 'file exists'; fi;
! ls cat.jpg -lh

In [0]:
import imageio
import matplotlib.pyplot as plt

catjpgfile = 'cat.jpg'
img = imageio.imread(catjpgfile)
print(img)
print(img.shape)

In [0]:
img_tinted = np.average(img,weights=[0.299,0.587,0.114],axis=2)
print(img_tinted.shape)

In [0]:
# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
#plt.imshow(np.uint8(img_tinted), cmap=plt.get_cmap('gray'))
plt.imshow(np.uint8(img_tinted), cmap='gray')
#plt.imshow(img_tinted)
plt.show()

## 3. Scipy Example: Regression

In [0]:
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 5, 7, 10, 15])
y = np.array([2, 6, 7, 9, 14, 19]) 
slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)

In [0]:
plt.plot(x,y,'or')
yh = x*slope + intercept
plt.plot(x, yh, '-b')
plt.show()